[package]
name = "playground"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.9.5", features = ["rustls-tls"], default-features = false }
failure = "0.1.2"
serde = "1.0.80"
serde_derive = "1.0.80"
futures = "0.1.25"
